### ISSUE TITLE
app crash on Nearby API leakage

### ISSUE THREAD

**Issue by niehusst** [niehusst/partyq#93]
App crashes when Nearby tries to do something with a connected guest that was connected via Bluetooth but then switched to wifi?

```
android.app.ServiceConnectionLeaked: Service com.google.android.gms.nearby.discovery.service.DiscoveryService has leaked ServiceConnection android.bluetooth.BluetoothA2dp$2@720f557 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1133)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1027)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1308)
        at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1298)
        at android.content.ContextWrapper.bindServiceAsUser(ContextWrapper.java:611)
        at android.content.ContextWrapper.bindServiceAsUser(ContextWrapper.java:611)
        at android.content.ContextWrapper.bindServiceAsUser(ContextWrapper.java:611)
        at android.content.ContextWrapper.bindServiceAsUser(ContextWrapper.java:611)
        at android.content.ContextWrapper.bindServiceAsUser(ContextWrapper.java:611)
        at android.bluetooth.BluetoothA2dp.doBind(BluetoothA2dp.java:197)
        at android.bluetooth.BluetoothA2dp.<init>(BluetoothA2dp.java:190)
        at android.bluetooth.BluetoothAdapter.getProfileProxy(BluetoothAdapter.java:1854)
        at bxtw.<init>(:com.google.android.gms@203915019@20.39.15 (040400-335085812):6)
        at aisg.a(:com.google.android.gms@203915019@20.39.15 (040400-335085812):64)
        at aihm.c(:com.google.android.gms@203915019@20.39.15 (040400-335085812):3)
        at aihm.b(:com.google.android.gms@203915019@20.39.15 (040400-335085812):3)
        at aihm.a(:com.google.android.gms@203915019@20.39.15 (040400-335085812):9)
        at aihm.a(:com.google.android.gms@203915019@20.39.15 (040400-335085812):8)
        at aixa.<init>(:com.google.android.gms@203915019@20.39.15 (040400-335085812):6)
        at aisg.a(:com.google.android.gms@203915019@20.39.15 (040400-335085812):35)
        at aihm.c(:com.google.android.gms@203915019@20.39.15 (040400-335085812):3)
        at aihm.b(:com.google.android.gms@203915019@20.39.15 (040400-335085812):3)
        at aihm.a(:com.google.android.gms@203915019@20.39.15 (040400-335085812):9)
        at aihm.a(:com.google.android.gms@203915019@20.39.15 (040400-335085812):8)
        at ajfu.<init>(:com.google.android.gms@203915019@20.39.15 (040400-335085812):7)
        at aisg.a(:com.google.android.gms@203915019@20.39.15 (040400-335085812):66)
        at aihm.c(:com.google.android.gms@203915019@20.39.15 (040400-335085812):3)
        at aihm.b(:com.google.android.gms@203915019@20.39.15 (040400-335085812):3)
        at aihm.a(:com.google.android.gms@203915019@20.39.15 (040400-335085812):9)
        at aihm.a(:com.google.android.gms@203915019@20.39.15 (040400-335085812):8)
        at com.google.android.gms.nearby.discovery.service.DiscoveryChimeraService.onCreate(:com.google.android.gms@203915019@20.39.15 (040400-335085812):2)
        at ctr.onCreate(:com.google.android.gms@203915019@20.39.15 (040400-335085812):1)
        at qps.onCreate(:com.google.android.gms@203915019@20.39.15 (040400-335085812):4)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3067)
        at android.app.ActivityThread.-wrap4(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5728)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

**Comment by niehusst** [comment]
It may be possible that the app crash causes this leakage, rather than the other way around. Would require more logs/investigation
